### ISSUE TITLE
Does `labelhook` option make `tcolorbox`' `label is zlabel` option useless?

### ISSUE THREAD

**Issue by dbitouze** [gusbrs/zref-clever#19]
The documentation, section 7, states:

> However, the `labelhook` option (see Section 8) leverages the kernel’s label hook to also set a `\zlabel` when a standard `\label` is called, so that we can simply use `\label`s in our document and refer to them with either referencing system.

Does it mean the `tcolorbox`' `label is zlabel` option becomes useless?

**Comment by gusbrs** [comment]
Hi @dbitouze 

> Does it mean the `tcolorbox`' `label is zlabel` option becomes useless?

No it doesn't. First of all, on can always prefer to continue using `\zlabel` (you've probably seen it, but it is discussed in the "`\label` or `\zlabel`?" section of the manual). Second, the `tcolorbox` `label type` option won't work for `zref` unless `label is zlabel` is enabled. For two reasons, first `label type` with `label is label` presumes `cleveref` is loaded, and calls `\label` with an optional argument, so that if you only load `zref-clever` and use that option, you'll get an error. Second, `\zcsetup{reftype=...}` is only called with `label is zlabel`. In sum, you need `label is zlabel` to use `label type` with `zref-clever`. 

It would actually be good if this second restriction could be relaxed, but I think `tcolorbox`'s maintainer has already been generous enough with `zref-clever` specifics of late (see https://github.com/T-F-S/tcolorbox/issues/206 and https://github.com/T-F-S/tcolorbox/issues/230), I would not want to abuse. And there's also a technical problem in trying to generalize this, and it is the aforementioned fact that `tcolorbox` unconditionally calls `\label` with an optional argument if `label is label`, which requires `cleveref` because that's the only place which defines `\label` this way. So it would be somewhat tricky, and I'm not sure if worth the hassle.

**Comment by gusbrs** [comment]
If I know you, you are probably aware of this already, but for reference, in case anyone else drops by, there's some news in this area: https://github.com/T-F-S/tcolorbox/issues/295

The answer to the issue's title question is still "no". `tcolorbox`'s `label is zlabel` used to be critical for `zref-clever` (to be able to set a type), and won't be anymore. With the coming release of `tcolorbox`, things should "just work". `label is zlabel`  is still useful though for those who prefer to explicitly use `\zlabel`, or don't want to use the `labelhook` option, or want to work with plain `zref`, etc. But, of course, less so.
