### ISSUE TITLE
Russian language support

### ISSUE THREAD

**Issue by jemmybutton** [gusbrs/zref-clever#28]
I'd like to contribute the support for the Russian language to the package. I've translated all the lines with all the cases for Russian https://github.com/jemmybutton/zref-clever/commit/5a1c24487dd7e9d425442ff555dd38bd8c18d496 and it seems to work fine, but before creating a pull-request, I wanted to make sure if I need to add something else. E.g., I didn't create the testfiles (bc I don't quite understand how they work, tbh).

**Comment by gusbrs** [comment]
Hi @jemmybutton , this is much welcome, thank you. And nice to see another language with declension (and 6 of them!).

As far as I can tell, formally, it looks good. But I haven't the faintest idea or Russian, so I can only trust you with the content. If you feel comfortable with a PR, that is welcome, but if you prefer, I can handle things with the content you provide. And I can also handle test files, this is indeed a little hard for those not initiated in `l3build`, and there's really no need to burden you with them. Though I might ask you to verify results of tests, of course, since I cannot possibly check certain things myself.

Also, before we proceed, and if you haven't done it already, please read carefully the section "Localization guidelines" in the code documentation (http://mirrors.ctan.org/macros/latex/contrib/zref-clever/zref-clever-code.pdf or `texdoc zref-clever-code`), and adjust things accordingly if needed.

**Comment by jemmybutton** [comment]
Great! As suggested in the guidelines I mostly used `cleveref`'s Russian translation as reference, with a couple of small deviations. I do indeed have some doubts regarding footnotes and endnotes, maybe it makes sense to keep them identical. I will double-check everything, make necessary changes, and create a PR within a couple of days.

**Comment by gusbrs** [comment]
Great! I'm looking forward to it.

Using `cleveref` as reference is fine (though, if so, please acknowledge your source(s) in the corresponding code documentation in the .dtx), but please also check consistency with `babel` captions/names (see https://mirrors.ctan.org/macros/latex/contrib/babel-contrib/russian/russianb.ldf).

**Comment by jemmybutton** [comment]
Done. There's, of course, a chance that some mistakes still linger. Please, feel free to contact me to make any corrections/additions.

**Comment by jemmybutton** [comment]
Sorry, I completely forgot that the docs don't seem to have support for Cyrillic. This https://github.com/jemmybutton/zref-clever/commit/49ef003f8387c343b81e78d6ba8d4b5406a2e2df seems to fix it, but not sure if it's the way you'd like to go about this.

**Comment by gusbrs** [comment]
I'll comment on the PR.

**Comment by gusbrs** [comment]
Implemented at https://github.com/gusbrs/zref-clever/pull/29. Thank you!

**Comment by jemmybutton** [comment]
@gusbrs Thank you so much!
