### ISSUE TITLE
question: ordering issues?

### ISSUE THREAD

**Issue by dkwo** [gusbrs/zref-clever#34]
I'm trying to use zref-clever with a journal-provided article class that loads hyperref and defines theorems _before_ I can load zref-clever in my tex file. It seems to work fine, but do you know whether there's any caveat?

Thanks.

**Comment by gusbrs** [comment]
I don't expect to be any problem, since `zref-clever` does not redefine `\newtheorem` or any `hyperref` or kernel macros. As of yet, I haven't received any load order complaints for `zref-clever`. But I don't know anything about your actual environment and what this "journal-provided article class" is.

In the future, please bear in mind that this is an issue tracker. For support or questions like this, there are more appropriate places, like TeX.SX.
