### ISSUE TITLE
Add common theorem-like reference types

### ISSUE THREAD

**Issue by niluxv** [gusbrs/zref-clever#7]
Hi @gusbrs ,

I noticed that, while the default language files are pretty extensive, some common theorem-like environments (e.g. `axiom`, `notation`, and some more) are lacking. Would you be interested in a PR which adds some reference types? I would be able to submit additions for the English, Dutch and German language files, but not for the other languages...

**Comment by gusbrs** [comment]
Hi @niluxv , indeed the language files are not exhaustive, and there's actually no intention of being so (because, well, it would be impossible anyway). I wanted the language files to cover types for well established packages and, in the case of math environments, some traditional ones, the most commonly used. And I think the current set is already quite generous in covering a somewhat wide range of possibilities. Besides, there's full support for users adding new types, and it is trivial to do so. All in all, there's a balance to reach in this coverage of different types -- user convenience vs. maintenance burden -- and my current feeling is that I might have already overstreched a bit in the original set. So, I appreciate your offer, and thank you very much for it, but I count on your understanding in keeping the current set as it is.

**Comment by niluxv** [comment]
Okay, no problem. I'll close the issue then.
